name: Deploy DAGs via GitActions

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy EC2 via GitActions
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.airflow_EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.airflow_SSH_PRIVATE_KEY }}
          port: 22
          
          script: |
            cd /home/ubuntu/catchdata-airflow
            git fetch
            git pull